language: java

env:
  - MOZ-HEADLESS=1
  
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
  
script:
  - chmod +x resources/geckodriver
  - chmod +x resources/chromedriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - mvn clean integration-test
